# Generated by Django 3.0.3 on 2020-02-15 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doogy_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wall',
            name='user',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Wall',
        ),
    ]
